-- MySQL Script generated by MySQL Workbench - corrigido
-- Data: 02/07/2025
-- Modelo: loja_vendas

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema loja_vendas
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `loja_vendas` DEFAULT CHARACTER SET utf8 ;
USE `loja_vendas` ;

-- -----------------------------------------------------
-- Table `Categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Categorias` ;

CREATE TABLE IF NOT EXISTS `Categorias` (
  `ID` INT AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID`)
);

-- -----------------------------------------------------
-- Table `Fornecedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Fornecedores` ;

CREATE TABLE IF NOT EXISTS `Fornecedores` (
  `ID` INT AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  `Contato` VARCHAR(100),
  PRIMARY KEY (`ID`)
);

-- -----------------------------------------------------
-- Table `Produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Produtos` ;

CREATE TABLE IF NOT EXISTS `Produtos` (
  `ID` INT AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  `Descricao` TEXT,
  `PrecoUnitario` DECIMAL(10,2) NOT NULL,
  `QuantidadeEstoque` INT DEFAULT 0,
  `ID_Categoria` INT,
  `ID_Fornecedor` INT,
  PRIMARY KEY (`ID`),
  INDEX (`ID_Categoria`),
  INDEX (`ID_Fornecedor`),
  CONSTRAINT `fk_produtos_categoria`
    FOREIGN KEY (`ID_Categoria`) REFERENCES `Categorias` (`ID`),
  CONSTRAINT `fk_produtos_fornecedor`
    FOREIGN KEY (`ID_Fornecedor`) REFERENCES `Fornecedores` (`ID`)
);

-- -----------------------------------------------------
-- Table `Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Clientes` ;

CREATE TABLE IF NOT EXISTS `Clientes` (
  `ID` INT AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  `Endereco` VARCHAR(200),
  `Telefone` VARCHAR(20),
  `Email` VARCHAR(100),
  PRIMARY KEY (`ID`)
);

-- -----------------------------------------------------
-- Table `Funcionarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Funcionarios` ;

CREATE TABLE IF NOT EXISTS `Funcionarios` (
  `ID` INT AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  `Cargo` VARCHAR(50),
  `Salario` DECIMAL(10,2),
  PRIMARY KEY (`ID`)
);

-- -----------------------------------------------------
-- Table `Vendas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Vendas` ;

CREATE TABLE IF NOT EXISTS `Vendas` (
  `ID` INT AUTO_INCREMENT,
  `DataVenda` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `ID_Cliente` INT NOT NULL,
  `ValorTotal` DECIMAL(10,2) DEFAULT 0,
  `ID_Funcionario` INT,
  PRIMARY KEY (`ID`),
  INDEX (`ID_Cliente`),
  INDEX (`ID_Funcionario`),
  CONSTRAINT `fk_vendas_cliente`
    FOREIGN KEY (`ID_Cliente`) REFERENCES `Clientes` (`ID`),
  CONSTRAINT `fk_vendas_funcionario`
    FOREIGN KEY (`ID_Funcionario`) REFERENCES `Funcionarios` (`ID`)
);

-- -----------------------------------------------------
-- Table `ItensVenda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ItensVenda` ;

CREATE TABLE IF NOT EXISTS `ItensVenda` (
  `ID` INT AUTO_INCREMENT,
  `ID_Venda` INT NOT NULL,
  `ID_Produto` INT NOT NULL,
  `Quantidade` INT DEFAULT 1,
  `PrecoUnitarioVenda` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX (`ID_Venda`),
  INDEX (`ID_Produto`),
  CONSTRAINT `fk_itensvenda_venda`
    FOREIGN KEY (`ID_Venda`) REFERENCES `Vendas` (`ID`),
  CONSTRAINT `fk_itensvenda_produto`
    FOREIGN KEY (`ID_Produto`) REFERENCES `Produtos` (`ID`)
);

-- -----------------------------------------------------
-- Restaura configurações iniciais
-- -----------------------------------------------------
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
